name: "godot-ci export"
on: push

permissions:
  contents: write
  pages: write

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.7.1
  EXPORT_NAME: Jammin
  PROJECT_PATH: "."
  ITCH_USER: michaelg1223
  ITCH_GAME: count-down-to-jam
  VERSION: 1.0.0
  WIN_PACKAGE: build/windows
  LIN_PACKAGE: build/linux
  WEB_PACKAGE: build/web
  

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows
      - name: Download butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler platform based on runner OS
          BUTLER_PLATFORM="linux-amd64"
          BUTLER_EXEC="butler"
          mkdir ./tools 2>/dev/null || true
          pushd tools
            curl -sSLfo ./butler.zip "https://broth.itch.zone/butler/${BUTLER_PLATFORM}/LATEST/archive/default"
            unzip butler.zip
            chmod +x ./${BUTLER_EXEC}
          popd
          ./tools/${BUTLER_EXEC} -V
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler executable name based on runner OS
          BUTLER_EXEC="butler"
          versionArgument=""
          if [ -n "${{ env.VERSION }}" ]; then
            versionArgument="--userversion ${{ env.VERSION }}"
          fi
          ./tools/${BUTLER_EXEC} push \
          "${{ env.WIN_PACKAGE }}" \
          ${{ env.ITCH_USER }}/${{ env.ITCH_USER }}:windows ${versionArgument}


  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
      - name: Install curl
        run: |
          sudo apt update
          sudo apt install curl
      - name: Install curl
        run: |
          sudo apt update
          sudo apt install curl
      - name: Download butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler platform based on runner OS
          BUTLER_PLATFORM="linux-amd64"
          BUTLER_EXEC="butler"
          mkdir ./tools 2>/dev/null || true
          pushd tools
            curl -sSLfo ./butler.zip "https://broth.itch.zone/butler/${BUTLER_PLATFORM}/LATEST/archive/default"
            unzip butler.zip
            chmod +x ./${BUTLER_EXEC}
          popd
          ./tools/${BUTLER_EXEC} -V
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler executable name based on runner OS
          BUTLER_EXEC="butler"
          versionArgument=""
          if [ -n "${{ env.VERSION }}" ]; then
            versionArgument="--userversion ${{ env.VERSION }}"
          fi
          ./tools/${BUTLER_EXEC} push \
          "${{ env.LIN_PACKAGE }}" \
          ${{ env.ITCH_USER }}/${{ env.ITCH_USER }}:linux ${versionArgument}

  export-web:
    name: Web Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
      - name: Install curl
        run: |
          sudo apt update
          sudo apt install curl
      - name: Download butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler platform based on runner OS
          BUTLER_PLATFORM="linux-amd64"
          BUTLER_EXEC="butler"
          mkdir ./tools 2>/dev/null || true
          pushd tools
            curl -sSLfo ./butler.zip "https://broth.itch.zone/butler/${BUTLER_PLATFORM}/LATEST/archive/default"
            unzip butler.zip
            chmod +x ./${BUTLER_EXEC}
          popd
          ./tools/${BUTLER_EXEC} -V
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        shell: bash
        run: |
          # Set butler executable name based on runner OS
          BUTLER_EXEC="butler"
          versionArgument=""
          if [ -n "${{ env.VERSION }}" ]; then
            versionArgument="--userversion ${{ env.VERSION }}"
          fi
          ./tools/${BUTLER_EXEC} push \
          "${{ env.WEB_PACKAGE }}" \
          ${{ env.ITCH_USER }}/${{ env.ITCH_USER }}:linux ${versionArgument}